// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_app.jsx";
import * as $1 from "./routes/index.jsx";
import * as $2 from "./routes/result.jsx";
import * as $3 from "./routes/select.jsx";

const manifest = {
  routes: {
    "./routes/_app.jsx": $0,
    "./routes/index.jsx": $1,
    "./routes/result.jsx": $2,
    "./routes/select.jsx": $3,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
